let DATA={matches:[],count:0,generated_at:'',reports:[],reviews:[]};
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&','<':'<','>':'>','"':'"',"'":'&#39;'}[c]));}
function switchView(v){document.querySelectorAll('.view').forEach(e=>e.classList.remove('active'));document.getElementById('view-'+v).classList.add('active');document.querySelectorAll('nav button').forEach(b=>b.classList.remove('active'));document.getElementById('nav-'+v).classList.add('active');}
function toggleMatch(i){var el=document.getElementById('m'+i);if(el)el.classList.toggle('open');}
let betSlip=[],curLeague='all';
const PLAY_NAME={spf:'胜平负',rqspf:'让球',zjq:'总进球',bqc:'半全场',bf:'比分'};
function betKey(c,p,o){return c+'|'+p+'|'+o;}
function toggleBet(el,code,play,opt,label,odds){const key=betKey(code,play,opt);const i=betSlip.findIndex(b=>b.key===key);if(i>=0){betSlip.splice(i,1);el.classList.remove('sel');}else{betSlip.push({key,code,play,opt,label,odds});el.classList.add('sel');}renderSlip();}
function removeBet(key){betSlip=betSlip.filter(b=>b.key!==key);renderSlip();}
function clearSlip(){betSlip=[];document.querySelectorAll('.sel').forEach(e=>e.classList.remove('sel'));renderSlip();}
function saveSlip(){try{localStorage.setItem('betSlip',JSON.stringify(betSlip))}catch(e){}}
function calcWin(mode,mul){if(!betSlip.length)return 0;if(mode==='single')return betSlip.reduce((s,b)=>s+2*parseFloat(b.odds),0)*mul;return 2*betSlip.reduce((s,b)=>s*parseFloat(b.odds),1)*mul;}
function renderSlip(){const wrap=document.getElementById('betslip');document.getElementById('bs-count').textContent=betSlip.length;if(!betSlip.length){wrap.style.display='none';document.body.classList.remove('has-slip');return;}wrap.style.display='block';document.body.classList.add('has-slip');document.getElementById('bs-list').innerHTML=betSlip.map(b=>{const m=DATA.matches.find(x=>x.code===b.code);const mm=m?esc(m.home)+' vs '+esc(m.away):esc(b.code);return '<span class="bs-item" onclick="removeBet(\''+b.key+'\')">'+mm+' · '+esc(b.label)+' <b style="color:var(--gold)">'+esc(b.odds)+'</b><span class="x">×</span></span>';}).join('');const mul=parseInt(document.getElementById('bs-mul').value)||1;const mode=document.getElementById('bs-mode').value;document.getElementById('bs-win').textContent='¥'+calcWin(mode,mul).toFixed(2);}
function copySlip(){if(!betSlip.length)return;const mul=parseInt(document.getElementById('bs-mul').value)||1;const mode=document.getElementById('bs-mode').value;const lines=betSlip.map((b,i)=>{const m=DATA.matches.find(x=>x.code===b.code);return (i+1)+'. '+(m?m.home+' vs '+m.away:b.code)+' '+(PLAY_NAME[b.play]||b.play)+' '+b.label+' @'+b.odds;}).join('\n');const t='【竞彩过关】'+(mode==='single'?'单关':betSlip.length+'串1')+' ×'+mul+'倍\n'+lines+'\n最高奖金：¥'+calcWin(mode,mul).toFixed(2);if(navigator.clipboard)navigator.clipboard.writeText(t).then(()=>alert('已复制'));else alert(t);}
function cell(code,play,opt,label,odds,cls){if(!odds)return '';const key=betKey(code,play,opt);return '<div class="qcell" data-key="'+key+'" onclick="toggleBet(this,\''+code+'\',\''+play+'\',\''+opt+'\',\''+label+'\',\''+odds+'\')"><div class="l">'+label+'</div><div class="v '+cls+'">'+esc(odds)+'</div></div>';}
function playsBlock(m){const p=m.plays||{};let html='';if(p.zjq){html+='<div class="sect"><h3>总进球</h3><div class="play-grid">'+Object.entries(p.zjq).map(([k,v])=>{const lab=k==='7'?'7+球':k+'球';return '<div class="p" onclick="toggleBet(this,\''+m.code+'\',\'zjq\',\''+k+'\',\''+lab+'\',\''+v+'\')"><div class="s">'+lab+'</div><div class="o">'+esc(v)+'</div></div>';}).join('')+'</div></div>';}if(!html)html='<div class="muted">暂无玩法数据（比分/总进球/半全场）</div>';return html;}
function h2hBlock(h){if(!h)return '<div class="muted">暂无交战历史</div>';let html=h.summary?'<div class="summary-bar">'+esc(h.summary)+'</div>':'';if(h.rows&&h.rows.length){html+='<table><thead><tr><th>日期</th><th>赛事</th><th>主队</th><th>比分</th><th>客队</th><th>半场</th><th>亚盘</th><th>赛果</th></tr></thead><tbody>'+h.rows.map(r=>'<tr><td>'+esc(r.date)+'</td><td>'+esc(r.league)+'</td><td>'+esc(r.home)+'</td><td class="hl">'+esc(r.score)+'</td><td>'+esc(r.away)+'</td><td>'+esc(r.half)+'</td><td>'+esc(r.hcap||'')+'</td><td>'+esc(r.result||'')+'</td></tr>').join('')+'</tbody></table>';}return html||'<div class="muted">暂无交战历史</div>';}
function formBlock(form){if(!form)return '<div class="muted">暂无近期战绩</div>';let html='';for(const [team,v] of Object.entries(form)){html+='<div class="sect"><h3>'+esc(team)+(v.summary?' <span class="muted">'+esc(v.summary)+'</span>':'')+'</h3>';if(v.rows&&v.rows.length){html+='<table><thead><tr><th>日期</th><th>赛事</th><th>主队</th><th>比分</th><th>客队</th><th>盘口</th><th>半场</th><th>赛果</th></tr></thead><tbody>'+v.rows.map(r=>'<tr><td>'+esc(r.date)+'</td><td>'+esc(r.league)+'</td><td>'+esc(r.home)+'</td><td class="hl">'+esc(r.score)+'</td><td>'+esc(r.away)+'</td><td>'+esc(r.hcap||'')+'</td><td>'+esc(r.half)+'</td><td>'+esc(r.result||'')+'</td></tr>').join('')+'</tbody></table>';}else html+='<div class="muted">无数据</div>';html+='</div>';}return html;}
function recBlock(m){const r=m.rec;if(!r)return '';const star='★'.repeat(r.star||0)+'☆'.repeat(Math.max(0,5-(r.star||0)));const reasons=(r.reasons||[]).map(x=>'<li>'+esc(x)+'</li>').join('');return '<div class="sect"><h3>25维推荐分析</h3><div class="rec-head"><span class="rec-dir">'+esc(r.direction)+'</span><span class="rec-star">'+star+'</span><span class="rec-stake">'+(r.stake||0)+'u</span></div>'+(reasons?'<div class="rec-reasons"><b>关键依据：</b><ul>'+reasons+'</ul></div>':'')+'</div>';}
function matchCard(m,idx){const rq=m.rq==null?'':String(m.rq);const t1=m.date?m.date.slice(5)+' '+(m.time||''):(m.code||'');const spf=m.spf||{},rqspf=m.rqspf||{};const spfRow=cell(m.code,'spf','win','主胜',spf.win,'win')+cell(m.code,'spf','draw','平',spf.draw,'draw')+cell(m.code,'spf','lose','客胜',spf.lose,'lose');const rqRow=cell(m.code,'rqspf','win','让胜',rqspf.win,'win')+cell(m.code,'rqspf','draw','让平',rqspf.draw,'draw')+cell(m.code,'rqspf','lose','让负',rqspf.lose,'lose');const star=m.rec?('★'.repeat(m.rec.star||0)):'';const rec=m.rec?'<span class="rec-tag"><span class="rec-dir">'+esc(m.rec.direction)+'</span><span class="rec-star">'+star+'</span></span>':'';return '<div class="match" id="m'+idx+'"><div class="match-head" onclick="toggleMatch('+idx+')"><div class="no"><span class="tag">'+esc(m.code)+'</span><div class="dt">'+esc(t1)+'</div></div><div class="league">'+esc(m.league||'')+'</div><div class="teams"><span class="t"><span class="n">'+esc(m.home)+'</span></span><span class="vs">VS</span><span class="t"><span class="n">'+esc(m.away)+'</span></span></div><div class="odds-2row"><div class="orow"><span class="rq-tag">0</span>'+spfRow+'</div><div class="orow"><span class="rq-tag">'+esc(rq)+'</span>'+rqRow+'</div></div>'+rec+'<span class="arrow">▾</span></div><div class="match-body" id="mb'+idx+'">'+recBlock(m)+'<div class="plays-area">'+playsBlock(m)+'</div><div class="tabpane active" style="display:block;padding:16px"><div class="sect"><h3>交战记录</h3>'+h2hBlock(m.h2h)+'</div><div class="sect"><h3>近6场</h3>'+formBlock(m.form)+'</div></div></div></div>';}
function filterLeague(l){curLeague=l;render();}
function render(){const d=DATA;document.getElementById('upd').textContent=d.generated_at||'';document.getElementById('cnt').textContent='共 '+(d.count||(d.matches||[]).length)+' 场';const list=(d.matches||[]).filter(m=>curLeague==='all'||(m.league||'其他')===curLeague);const leagues=[...new Set((d.matches||[]).map(m=>m.league||'其他').filter(Boolean))];document.getElementById('league-filter').innerHTML='<button class="'+(curLeague==='all'?'active':'')+'" onclick="filterLeague(\'all\')">全部</button>'+leagues.map(l=>'<button class="'+(curLeague===l?'active':'')+'" onclick="filterLeague(\''+l+'\')">'+esc(l)+'</button>').join('');document.getElementById('app').innerHTML=list.map((m,i)=>matchCard(m,i)).join('')||'<div class="empty">暂无赛程</div>';let h='';(d.reports||[]).forEach(r=>{h+='<div class="rv-card open"><div class="rv-head"><span class="d">'+esc(r.date||'')+'</span><span class="t">'+esc(r.title||'推荐')+'</span><span class="badge">推荐</span></div><div class="rv-body">';if(r.ops)h+='<table><thead><tr><th>场次</th><th>对阵</th><th>结论</th><th>注码</th></tr></thead><tbody>'+r.ops.map(x=>'<tr><td>'+esc(x.code)+'</td><td>'+esc(x.match)+'</td><td>'+esc(x.concl)+'</td><td>'+esc(x.bet)+'</td></tr>').join('')+'</tbody></table>';h+='</div></div>';});(d.reviews||[]).forEach(r=>{h+='<div class="rv-card open"><div class="rv-head"><span class="d">'+esc(r.date||'')+'</span><span class="t">'+esc(r.title||'复盘')+'</span><span class="badge">复盘</span></div><div class="rv-body">';if(r.results)h+='<table><thead><tr><th>场次</th><th>对阵</th><th>全场</th><th>半场</th></tr></thead><tbody>'+r.results.map(x=>'<tr><td>'+esc(x.code)+'</td><td>'+esc(x.match)+'</td><td>'+esc(x.full)+'</td><td>'+esc(x.half)+'</td></tr>').join('')+'</tbody></table>';h+='</div></div>';});document.getElementById('rv-app').innerHTML=h||'<div class="empty">暂无复盘/推荐</div>';renderSlip();}
function loadPart(i){return fetch('./m'+i+'.json',{cache:'no-store'}).then(function(r){return r.ok?r.json():null;}).catch(function(){return null;});}
Promise.all([loadPart(0),loadPart(1),loadPart(2)]).then(function(parts){parts=parts.filter(Boolean);if(!parts.length)throw new Error('无数据文件');DATA={generated_at:parts[0].generated_at,count:parts.reduce(function(s,p){return s+(p.matches||[]).length;},0),matches:parts.reduce(function(a,p){return a.concat(p.matches||[]);},[]),reports:parts[0].reports||[],reviews:parts[0].reviews||[]};window.DATA=DATA;render();}).catch(function(e){document.getElementById('app').innerHTML='<div class="empty">数据加载失败：'+esc(e)+'</div>';});
