(function(){
var filter={all:'all',bk:'all'};
function jcTag(on){return on?'<span class="hub-tag jc">竞彩</span>':'<span class="hub-tag njc">非竞彩</span>';}
function statusChip(s){if(s==='完')return'<span class="hub-st done">完</span>';if(s==='进行')return'<span class="hub-st live">进行</span>';return'<span class="hub-st wait">未</span>';}
function injectCss(){if(document.getElementById('hub-css'))return;var s=document.createElement('style');s.id='hub-css';s.textContent='.hub-bar{display:flex;gap:8px;flex-wrap:wrap;margin:0 0 12px}.hub-bar button{background:#1a2438;border:1px solid #26324d;color:#8b98b5;border-radius:14px;padding:4px 12px;cursor:pointer;font-size:12px}.hub-bar button.on{background:#f5b942;color:#141b2e;border-color:#f5b942;font-weight:700}.hub-card{background:#182136;border:1px solid #26324d;border-radius:10px;padding:12px 14px;margin-bottom:10px;display:flex;gap:10px;align-items:center;flex-wrap:wrap}.hub-tag{font-size:10px;padding:1px 6px;border-radius:4px;font-weight:700}.hub-tag.jc{background:rgba(245,185,66,.18);color:#f5b942}.hub-tag.njc{background:rgba(77,163,255,.15);color:#4da3ff}.hub-st{font-size:11px;padding:1px 6px;border-radius:4px}.hub-st.done{background:rgba(46,194,126,.15);color:#2ec27e}.hub-st.live{background:rgba(255,90,95,.15);color:#ff5a5f}.hub-st.wait{background:#23314f;color:#8b98b5}.hub-score{font-size:20px;font-weight:800;color:#f5b942;min-width:72px;text-align:center}.hub-vs{flex:1;min-width:160px}.hub-vs .ln{font-size:11px;color:#8b98b5}.hub-vs .tm{font-weight:700;font-size:15px}.hub-res .win{color:#ff5a5f;font-weight:700}.hub-res .draw{color:#2ec27e;font-weight:700}.hub-res .lose{color:#4da3ff;font-weight:700}';document.head.appendChild(s);}
function jcMatches(){return((window.DATA&&DATA.matches)||[]).map(function(m){return{code:m.code,sport:'fb',jc:true,league:m.league,date:m.date,time:m.time,home:m.home,away:m.away,status:(m.score&&m.score!=='—')?'完':'未',score:(m.score&&m.score!=='—')?m.score:'',half:m.half||'',spf:m.spf};});}
function allFootball(){return jcMatches().concat((window.HUB&&HUB.football_extra)||[]);}
function allBasket(){return(window.HUB&&HUB.basketball)||[];}
function pass(list,key){var f=filter[key];if(f==='jc')return list.filter(function(x){return x.jc;});if(f==='njc')return list.filter(function(x){return!x.jc;});return list;}
function rowFb(m){var sc=m.score?('<div class="hub-score">'+esc(m.score)+'</div>'):'<div class="hub-score" style="color:#5c6884">VS</div>';return'<div class="hub-card">'+statusChip(m.status)+jcTag(m.jc)+'<div class="hub-vs"><div class="ln">'+esc(m.code)+' · '+esc(m.league||'')+' · '+esc((m.date||'').slice(5)+' '+(m.time||''))+'</div><div class="tm">'+esc(m.home)+' vs '+esc(m.away)+'</div></div>'+sc+'</div>';}
function rowBk(m){var sc=m.score?('<div class="hub-score">'+esc(m.score)+'</div>'):'<div class="hub-score" style="color:#5c6884">VS</div>';return'<div class="hub-card">'+statusChip(m.status)+jcTag(m.jc)+'<div class="hub-vs"><div class="ln">'+esc(m.code)+' · '+esc(m.league)+' · '+esc((m.date||'').slice(5)+' '+(m.time||''))+' · 客先</div><div class="tm">'+esc(m.away)+' @ '+esc(m.home)+'</div>'+(m.note?'<div class="ln">'+esc(m.note)+'</div>':'')+'</div>'+sc+'</div>';}
function resultMark(m){if(!m.score||m.status!=='完')return'<span class="muted">未出</span>';var p=String(m.score).split(/[:：-]/);if(p.length<2)return esc(m.score);var a=parseInt(p[0],10),b=parseInt(p[1],10);if(isNaN(a)||isNaN(b))return esc(m.score);if(m.sport==='bk'){if(b>a)return'<span class="win">主胜 '+esc(m.score)+'</span>';if(b<a)return'<span class="lose">主负 '+esc(m.score)+'</span>';return'<span class="draw">平 '+esc(m.score)+'</span>';}if(a>b)return'<span class="win">主胜 '+esc(m.score)+'</span>';if(a<b)return'<span class="lose">客胜 '+esc(m.score)+'</span>';return'<span class="draw">平 '+esc(m.score)+'</span>';}
function rowRes(m){return'<div class="hub-card hub-res">'+jcTag(m.jc)+'<div class="hub-vs"><div class="ln">'+esc(m.code)+' · '+esc(m.league)+' · '+(m.sport==='bk'?'篮球':'足球')+'</div><div class="tm">'+(m.sport==='bk'?esc(m.away)+' @ '+esc(m.home):esc(m.home)+' vs '+esc(m.away))+'</div></div><div>'+resultMark(m)+'</div></div>';}
function bars(key){return'<div class="hub-bar"><button class="'+(filter[key]==='all'?'on':'')+'" onclick="hubFilter(\''+key+'\',\'all\')">全部</button><button class="'+(filter[key]==='jc'?'on':'')+'" onclick="hubFilter(\''+key+'\',\'jc\')">只看竞彩</button><button class="'+(filter[key]==='njc'?'on':'')+'" onclick="hubFilter(\''+key+'\',\'njc\')">只看非竞彩</button></div>';}
window.hubFilter=function(key,v){filter[key]=v;renderHub();};
window.renderHub=function(){injectCss();var fa=document.getElementById('hub-all');if(fa){var list=pass(allFootball(),'all');fa.innerHTML=bars('all')+'<div class="muted" style="margin-bottom:8px">足球全部 · '+list.length+'场</div>'+(list.map(rowFb).join('')||'<div class="empty">暂无</div>');}var bk=document.getElementById('hub-bk');if(bk){var bl=pass(allBasket(),'bk');bk.innerHTML=bars('bk')+'<div class="muted" style="margin-bottom:8px">篮球惯例客队在前 · '+bl.length+'场</div>'+(bl.map(rowBk).join('')||'<div class="empty">暂无</div>');}var rs=document.getElementById('hub-res');if(rs){var done=allBasket().filter(function(x){return x.status==='完';}).concat(allFootball().filter(function(x){return x.status==='完';}));rs.innerHTML='<div class="muted" style="margin-bottom:8px">已完赛 '+done.length+'场 · 足球今日多未开踢</div>'+(done.map(rowRes).join('')||'<div class="empty">暂无完场</div>');}};
var _sv=window.switchView;window.switchView=function(v){if(_sv)_sv(v);if(v==='all'||v==='bk'||v==='res')renderHub();};
var _r=window.render;if(typeof _r==='function'){window.render=function(){_r.apply(this,arguments);renderHub();}}
setTimeout(renderHub,600);
})();
