(function(){
var SAMPLES=[
"https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
"https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
"https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
"https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4",
"https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4",
"https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4"
];
function css(){if(document.getElementById('feed-css'))return;var s=document.createElement('style');s.id='feed-css';s.textContent='body.feed-on header{padding:6px 10px 0;background:rgba(10,12,20,.55);backdrop-filter:blur(10px);border-bottom:0}body.feed-on header .top{display:none}body.feed-on nav{justify-content:center;width:100%}body.feed-on nav button{color:#c9d2e3;font-size:13px;padding:8px 10px}body.feed-on .wrap{max-width:none;padding:0;margin:0}body.feed-on .betslip{display:none!important}#view-feed{height:calc(100dvh - 42px);background:#000}#feed-rail{height:100%;overflow-y:auto;scroll-snap-type:y mandatory;-webkit-overflow-scrolling:touch;scrollbar-width:none}#feed-rail::-webkit-scrollbar{display:none}.feed-item{position:relative;height:100%;min-height:calc(100dvh - 42px);scroll-snap-align:start;scroll-snap-stop:always;background:#000;overflow:hidden}.feed-item video{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;background:#000}.feed-shade{position:absolute;inset:0;background:linear-gradient(180deg,rgba(0,0,0,.25) 0%,rgba(0,0,0,.05) 30%,rgba(0,0,0,.72) 100%);pointer-events:none}.feed-meta{position:absolute;left:14px;right:72px;bottom:28px;z-index:2}.feed-code{display:inline-block;background:rgba(245,185,66,.92);color:#141b2e;font-weight:800;font-size:11px;padding:2px 7px;border-radius:4px;margin-bottom:8px}.feed-teams{font-size:22px;font-weight:800;line-height:1.25;text-shadow:0 2px 10px #000}.feed-teams small{display:block;font-size:12px;font-weight:600;color:#d7deea;margin-top:4px}.feed-odds{display:flex;gap:6px;margin-top:10px;flex-wrap:wrap}.feed-odds span{background:rgba(20,27,46,.72);border:1px solid rgba(255,255,255,.12);border-radius:8px;padding:5px 8px;font-size:12px}.feed-odds b{color:#f5b942}.feed-side{position:absolute;right:10px;bottom:90px;z-index:2;display:flex;flex-direction:column;gap:16px;align-items:center}.feed-side button{width:46px;height:46px;border-radius:50%;border:0;background:rgba(20,27,46,.55);color:#fff;font-size:11px;cursor:pointer}.feed-side button b{display:block;font-size:16px;line-height:1}.feed-hint{position:absolute;top:12px;left:0;right:0;text-align:center;font-size:11px;color:#c9d2e3;z-index:2}.feed-empty{height:100%;display:flex;align-items:center;justify-content:center;color:#8b98b5}';document.head.appendChild(s);}
function srcFor(i,m){try{var map=JSON.parse(localStorage.getItem('jczq_demo_live')||'{}');if(map[m.code])return map[m.code];}catch(e){}return SAMPLES[i%SAMPLES.length];}
function itemHtml(m,i){var sp=m.spf||{};var src=srcFor(i,m);var use= /\.mp4($|\?)/i.test(src)?src:SAMPLES[i%SAMPLES.length];return '<div class="feed-item" data-code="'+esc(m.code)+'"><video playsinline webkit-playsinline muted loop preload="metadata" src="'+use+'"></video><div class="feed-shade"></div>'+(i===0?'<div class="feed-hint">上滑看下一场 · 演示信号</div>':'')+'<div class="feed-meta"><span class="feed-code">'+esc(m.code)+' · '+esc(m.league||'')+'</span><div class="feed-teams">'+esc(m.home)+' vs '+esc(m.away)+'<small>'+esc((m.date||'')+' '+(m.time||''))+' · 点右侧进资料</small></div><div class="feed-odds"><span>主 <b>'+esc(sp.win||'—')+'</b></span><span>平 <b>'+esc(sp.draw||'—')+'</b></span><span>客 <b>'+esc(sp.lose||'—')+'</b></span></div></div><div class="feed-side"><button type="button" onclick="event.stopPropagation();feedLike(this)"><b>♥</b>赞</button><button type="button" onclick="event.stopPropagation();openFeedData(\''+m.code+'\')"><b>析</b>资料</button><button type="button" onclick="event.stopPropagation();switchView(\'tips\')"><b>¥</b>推荐</button></div></div>';}
window.feedLike=function(btn){btn.style.color='#ff5a5f';};
window.openFeedData=function(code){switchView('schedule');setTimeout(function(){var el=document.getElementById('m-'+code);if(el){el.classList.add('open');el.scrollIntoView({behavior:'smooth',block:'start'});}},80);};
function playVisible(){var rail=document.getElementById('feed-rail');if(!rail)return;var items=rail.querySelectorAll('.feed-item');var mid=rail.scrollTop+rail.clientHeight*0.45;items.forEach(function(it){var v=it.querySelector('video');if(!v)return;var top=it.offsetTop;var on=mid>=top&&mid<top+it.offsetHeight;if(on){v.muted=true;var p=v.play();if(p&&p.catch)p.catch(function(){});}else{v.pause();}});}
window.renderFeed=function(){css();var box=document.getElementById('feed-rail');if(!box)return;var list=((window.DATA&&DATA.matches)||[]).slice();if(!list.length){box.innerHTML='<div class="feed-empty">暂无今日场次</div>';return;}box.innerHTML=list.map(itemHtml).join('');box.onscroll=playVisible;box.ontouchend=playVisible;setTimeout(playVisible,200);};
var _sv=window.switchView;window.switchView=function(v){document.body.classList.toggle('feed-on',v==='feed');if(_sv)_sv(v);if(v==='feed')setTimeout(function(){renderFeed();playVisible();},30);else document.querySelectorAll('#feed-rail video').forEach(function(x){try{x.pause();}catch(e){}});};
var _render=window.render;if(typeof _render==='function'){window.render=function(){_render.apply(this,arguments);if(document.getElementById('view-feed')&&document.getElementById('view-feed').classList.contains('active'))renderFeed();};}
function boot(){css();if(document.getElementById('view-feed')&&document.getElementById('view-feed').classList.contains('active')){document.body.classList.add('feed-on');renderFeed();}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();setTimeout(boot,900);
})();
